FROM node:16.13.0

LABEL maintainer="jvinagr@teampurpose.com"
LABEL version="1.0"
LABEL description="aa-frontend-app \
docker image."

ADD . /app

WORKDIR /app

RUN npm install
RUN npm run build
RUN npm install pm2@latest -g

ENV HOST 0.0.0.0

EXPOSE 3000

ENTRYPOINT ["/app/entrypoint.sh"]
