//NOTE: Mock data that is emulating the data received from Composite API
export const paymentCards = {
  data: {
    cards: [
      {
        nameOnCard: 'string',
        cardType: {
          type: 'Debit',
          brand: 'VISA',
          level: 'string',
          bankName: 'Captial One Checking',
          countryISO: 'string',
        },
        cardReference: {
          id: 'string',
          type: 'REFERENCE',
          entity: 'CARD',
        },
        additionalProperties: {
          pan: 'string',
          cvv: 'string',
          cardLast4: '1234',
          cardExpiry: '2024-06-19',
          cardBin: 'string',
          track1Data: 'string',
          track2Data: 'string',
          track3Data: 'string',
          pinBlock: 'string',
          pinKSN: 'string',
          cardLimit: 0,
        },
        authorization: {
          collateralEligible: true,
          instantFundingEligible: true,
          estimatedFundsAvailability: 'string',
          avsResultCode: 'string',
          cardCollateralType: 'string',
        },
        customer: {
          purposeId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
          ssn: 'string',
          firstName: 'string',
          lastName: 'string',
          address: {
            purposeId: '43157b76-8e93-11ec-b909-0242ac120002',
            addressType: 'Home',
            address1: '11 W Main St',
            address2: 'Apartment #102',
            address3: 'near CVS',
            city: 'Wilmington',
            stateCode: 'DE',
            zipCode: 19801,
            active: true,
            dateCreated: '2021-12-02T00:00:00.000+02:00',
            dateModified: '2021-12-02T00:00:00.000+02:00',
          },
          account: {
            loanNumber: 'string',
            originationDate: '2022-06-16',
            originationAmount: 0,
            dueDate: '2024-06-16',
            originatingCenterNumber: 'string',
          },
        },
      },
      {
        nameOnCard: 'string',
        cardType: {
          type: 'Debit',
          brand: 'VISA',
          level: 'string',
          bankName: 'Captial One Checking',
          countryISO: 'string',
        },
        cardReference: {
          id: 'string',
          type: 'REFERENCE',
          entity: 'CARD',
        },
        additionalProperties: {
          pan: 'string',
          cvv: 'string',
          cardLast4: '6546',
          cardExpiry: '2022-06-15',
          cardBin: 'string',
          track1Data: 'string',
          track2Data: 'string',
          track3Data: 'string',
          pinBlock: 'string',
          pinKSN: 'string',
          cardLimit: 0,
        },
        authorization: {
          collateralEligible: true,
          instantFundingEligible: true,
          estimatedFundsAvailability: 'string',
          avsResultCode: 'string',
          cardCollateralType: 'string',
        },
        customer: {
          purposeId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
          ssn: 'string',
          firstName: 'string',
          lastName: 'string',
          address: {
            purposeId: '43157b76-8e93-11ec-b909-0242ac120002',
            addressType: 'Home',
            address1: '11 W Main St',
            address2: 'Apartment #102',
            address3: 'near CVS',
            city: 'Wilmington',
            stateCode: 'DE',
            zipCode: 19801,
            active: true,
            dateCreated: '2021-12-02T00:00:00.000+02:00',
            dateModified: '2021-12-02T00:00:00.000+02:00',
          },
          account: {
            loanNumber: 'string',
            originationDate: '2022-06-16',
            originationAmount: 0,
            dueDate: '2022-06-16',
            originatingCenterNumber: 'string',
          },
        },
      },
      {
        nameOnCard: 'string',
        cardType: {
          type: 'Debit',
          brand: 'VISA',
          level: 'string',
          bankName: 'Captial One Checking',
          countryISO: 'string',
        },
        cardReference: {
          id: 'string',
          type: 'REFERENCE',
          entity: 'CARD',
        },
        additionalProperties: {
          pan: 'string',
          cvv: 'string',
          cardLast4: '7567',
          cardExpiry: '2025-06-22',
          cardBin: 'string',
          track1Data: 'string',
          track2Data: 'string',
          track3Data: 'string',
          pinBlock: 'string',
          pinKSN: 'string',
          cardLimit: 0,
        },
        authorization: {
          collateralEligible: true,
          instantFundingEligible: true,
          estimatedFundsAvailability: 'string',
          avsResultCode: 'string',
          cardCollateralType: 'string',
        },
        customer: {
          purposeId: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
          ssn: 'string',
          firstName: 'string',
          lastName: 'string',
          address: {
            purposeId: '43157b76-8e93-11ec-b909-0242ac120002',
            addressType: 'Home',
            address1: '11 W Main St',
            address2: 'Apartment #102',
            address3: 'near CVS',
            city: 'Wilmington',
            stateCode: 'DE',
            zipCode: 19801,
            active: true,
            dateCreated: '2021-12-02T00:00:00.000+02:00',
            dateModified: '2021-12-02T00:00:00.000+02:00',
          },
          account: {
            loanNumber: 'string',
            originationDate: '2022-06-16',
            originationAmount: 0,
            dueDate: '2022-06-16',
            originatingCenterNumber: 'string',
          },
        },
      },
    ],
  },
};
