name: "Commit Stage"

on:
  pull_request:
  workflow_dispatch:

jobs:

  lint:
    name: Lint
    uses: ./.github/workflows/linter.yaml

  code-quality:
    name: Check Quality
    uses: ./.github/workflows/codeql-js.yaml
    needs: [lint]


