name: Lint Code Base

on:
  workflow_call:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node version 16.3.0
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: install project npm deps
        run: npm install

      - name: build app
        run: npm run build

      - name: run lint checker
        run: npm run lint

      - name: run format checker
        run: npm run lint:format

      - name: run style checker
        run: npm run lint:styles
